spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 10
    instances:
      naverSearch:
        baseConfig: default
      kakaoSearch:
        baseConfig: default
